In [1]:
# install modules
# %pip install pandas numpy matplotlib seaborn

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Tampilkan semua kolom
pd.set_option('display.max_columns', None)
pd.set_option('display.width', 200)

# Style grafik
sns.set_style('whitegrid')

In [3]:
df = pd.read_csv('../data/raw/AirBnB_BandungRaya_All.csv')

In [4]:
print(f"Jumlah baris: {df.shape[0]}")
print(f"Jumlah kolom: {df.shape[1]}")
print(f"\nNama kolom:")
for col in df.columns:
    print(f"  - {col}")

Jumlah baris: 572
Jumlah kolom: 6

Nama kolom:
  - nama
  - harga
  - rating
  - jumlah_review
  - link
  - wilayah

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 572 entries, 0 to 571
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   nama           572 non-null    str
 1   harga          572 non-null    str
 2   rating         557 non-null    str
 3   jumlah_review  572 non-null    int64
 4   link           572 non-null    str
 5   wilayah        572 non-null    str
dtypes: int64(1), str(5)
memory usage: 26.9 KB

In [6]:
df.head()

                                                nama          harga rating  jumlah_review                                              link       wilayah
0  Home in Cibeunying Kaler - Serene Pet-Friendly...   Rp 9,848,899      5             33  https://www.airbnb.com/rooms/1647712818622104523  Kota Bandung
1  Apartment in Cidadap - Dago, Ciumbuleuit, ITB ...   Rp 3,446,781   4.98            132  https://www.airbnb.com/rooms/1583745571091269827  Kota Bandung
2         Home in Sukajadi - Pine Breeze W/ Backyard  Rp 12,500,000   4.95            112  https://www.airbnb.com/rooms/1400529902543354123  Kota Bandung
3  Apartment in Cidadap - Abony | Bandung | PVJ |...   Rp 2,054,119   4.87             38  https://www.airbnb.com/rooms/1496783488914922824  Kota Bandung
4                     Home in Cidadap - Wangiterrace   Rp 9,883,877   4.98             51  https://www.airbnb.com/rooms/1504314537783385401  Kota Bandung

In [7]:
df.tail()

                                                  nama          harga rating  jumlah_review                                              link                  wilayah
567  Home in Kecamatan Sukajadi - Spacious 4BR Vill...   Rp 9,892,233   4.87             15  https://www.airbnb.com/rooms/1385448894932972520  Kabupaten Bandung Barat
568  Guest suite in Kecamatan Sukajadi - Beautiful ...   Rp 7,555,672   4.96             83  https://www.airbnb.com/rooms/1043230693114228999  Kabupaten Bandung Barat
569  Villa in Parompong - Montrii House - Alvar Sui...  Rp 16,054,260   4.97             35   https://www.airbnb.com/rooms/562498271762366418  Kabupaten Bandung Barat
570            Villa in Bandung - "Cipaku Rumah Villa"  Rp 14,721,183   4.95            329             https://www.airbnb.com/rooms/17773568  Kabupaten Bandung Barat
571  Apartment in Cicendo - 2BR Apartment Homy Livi...   Rp 2,929,844      5              6  https://www.airbnb.com/rooms/1672978017108497030  Kabupaten Bandung Barat

In [8]:

# Hapus "Rp ", hapus koma, dan ubah menjadi integer
df['harga'] = (
    df['harga']
    .str.replace('Rp', '', regex=False)
    .str.replace(',', '', regex=False)
    .str.strip()
    .astype(int)
)

# Ubah teks 'New' menjadi NaN (kosong), lalu ubah menjadi float
df['rating'] = pd.to_numeric(df['rating'].replace('New', np.nan), errors='coerce')

# 3. Cek hasilnya
print("--- INFO SETELAH DIBERSIHKAN ---")
df.info()

print("\n--- STATISTIK DESKRIPTIF ---")
display(df[['harga', 'rating', 'jumlah_review']].describe())

--- INFO SETELAH DIBERSIHKAN ---
<class 'pandas.DataFrame'>
RangeIndex: 572 entries, 0 to 571
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   nama           572 non-null    str
 1   harga          572 non-null    int64
 2   rating         520 non-null    float64
 3   jumlah_review  572 non-null    int64
 4   link           572 non-null    str
 5   wilayah        572 non-null    str
dtypes: float64(1), int64(2), str(3)
memory usage: 26.9 KB

--- STATISTIK DESKRIPTIF ---

              harga      rating  jumlah_review
count  5.720000e+02  520.000000     572.000000
mean   1.042942e+07    4.898615      64.956294
std    1.048505e+07    0.113492      88.344632
min    9.250000e+05    4.290000       0.000000
25%    4.072045e+06    4.850000      11.000000
50%    7.554086e+06    4.930000      33.000000
75%    1.200271e+07    4.990000      84.000000
max    9.400000e+07    5.000000     822.000000

In [9]:
# Ubah teks 'N/A' menjadi NaN (kosong), lalu ubah menjadi float
df['rating'] = pd.to_numeric(df['rating'].replace('N/A', np.nan), errors='coerce')

In [10]:
print("--- INFO SETELAH DIBERSIHKAN ---")
df.info()

print("\n--- STATISTIK DESKRIPTIF ---")
display(df[['harga', 'rating', 'jumlah_review']].describe())

--- INFO SETELAH DIBERSIHKAN ---
<class 'pandas.DataFrame'>
RangeIndex: 572 entries, 0 to 571
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   nama           572 non-null    str
 1   harga          572 non-null    int64
 2   rating         520 non-null    float64
 3   jumlah_review  572 non-null    int64
 4   link           572 non-null    str
 5   wilayah        572 non-null    str
dtypes: float64(1), int64(2), str(3)
memory usage: 26.9 KB

--- STATISTIK DESKRIPTIF ---

              harga      rating  jumlah_review
count  5.720000e+02  520.000000     572.000000
mean   1.042942e+07    4.898615      64.956294
std    1.048505e+07    0.113492      88.344632
min    9.250000e+05    4.290000       0.000000
25%    4.072045e+06    4.850000      11.000000
50%    7.554086e+06    4.930000      33.000000
75%    1.200271e+07    4.990000      84.000000
max    9.400000e+07    5.000000     822.000000

## Ringkasan Audit Data (Fase 1)

- **Dimensi Data**: Terdapat 572 baris dan 6 kolom.
- **Tipe Data**: 
  - `harga` awalnya berupa string (mengandung "Rp " dan koma) dan berhasil dibersihkan menjadi integer (`int64`).
  - `rating` awalnya berupa string (mengandung teks 'New') dan berhasil diubah menjadi desimal (`float64`).
- **Missing Values**:
  - `rating` memiliki 52 nilai kosong (sekitar 9%). Disebabkan oleh baris yang berupa hunian baru sehingga atribut di kolom rating berupa 'New' atau 'N/A'
  - Kolom lain tidak memiliki nilai kosong.
- **Distribusi Harga**:
  - Sangat *right-skewed* (condong ke kanan). Median harga adalah Rp 7.5 juta, namun rata-ratanya mencapai Rp 10.4 juta.
  - Terdapat harga ekstrem (outlier) hingga Rp 94 juta, dan terendah Rp 925 ribu. Transformasi logaritma (`log`) akan diperlukan pada fase pemodelan.
- **Distribusi Rating**:
  - Sangat terkonsentrasi di angka tinggi (rentang 4.29 hingga 5.0, dengan median 4.93). Standar deviasinya sangat kecil (0.11).
  - Hal ini menandakan bahwa variasi rating antar-listing sangat minim, sehingga prediksi harga berdasarkan rating murni mungkin akan memiliki korelasi yang lemah.
- **Lokasi & Wilayah**:
  - Kolom `wilayah` belum divalidasi. (Akan dicek normalisasinya di Fase 2).